// Pipeline data: node type catalog, default params, presets, and the pre-populated graph.

const NODE_TYPES = {
  raw_input: {
    title: 'Raw Atlas Input',
    category: 'Input',
    color: 'blue',
    icon: 'Image',
    short: 'IN',
    description: 'Source PNG file(s) from the AI generator. Drop in raw, untouched atlases.',
    inputs: [],
    outputs: [
      { id: 'atlas', label: 'raw atlas', kind: 'image' },
      { id: 'meta', label: 'source metadata', kind: 'json' },
    ],
    defaults: {
      source_label: 'sd-grass-v3.png',
      assumed_rows: 8,
      assumed_cols: 8,
      notes: 'AI generated 8×8 grass + dirt + props',
    },
    paramSchema: [
      { key: 'source_label', label: 'Source label', kind: 'text' },
      { key: 'assumed_rows', label: 'Assumed rows', kind: 'number', min: 1, max: 32 },
      { key: 'assumed_cols', label: 'Assumed cols', kind: 'number', min: 1, max: 32 },
      { key: 'notes', label: 'Notes', kind: 'textarea' },
    ],
  },
  clean: {
    title: 'Clean Tileset',
    category: 'Cleanup',
    color: 'teal',
    icon: 'Wrench',
    short: 'CL',
    description: 'Crop the AI grid, normalize tile size, resample to a clean atlas.',
    inputs: [{ id: 'atlas', label: 'raw atlas', kind: 'image', required: true }],
    outputs: [
      { id: 'atlas', label: 'cleaned 128px atlas', kind: 'image' },
      { id: 'meta', label: 'cleanup metadata', kind: 'json' },
    ],
    defaults: { rows: 8, cols: 8, tile_size: 128, grid_crop: true, resample: 'nearest' },
    paramSchema: [
      { key: 'rows', label: 'Rows', kind: 'number', min: 1, max: 32 },
      { key: 'cols', label: 'Cols', kind: 'number', min: 1, max: 32 },
      { key: 'tile_size', label: 'Tile size', kind: 'number', min: 8, max: 512, step: 8, suffix: 'px' },
      { key: 'grid_crop', label: 'Grid crop', kind: 'toggle' },
      { key: 'resample', label: 'Resample', kind: 'select', options: ['nearest', 'bilinear', 'bicubic', 'lanczos'] },
    ],
    warnings: (p) => p.resample !== 'nearest' ? [
      { level: 'warn', message: `Resample is "${p.resample}" — pixel art should use nearest-neighbor unless you intentionally test smoothing.` },
    ] : [],
  },
  classify: {
    title: 'Tile Classification',
    category: 'Cleanup',
    color: 'violet',
    icon: 'Tag',
    short: 'CM',
    description: 'Assign semantic classes to tile IDs (grass_base, dirt_base, transition, props).',
    inputs: [{ id: 'atlas', label: 'cleaned atlas', kind: 'image', required: true }],
    outputs: [
      { id: 'classmap', label: 'tile class map', kind: 'json' },
      { id: 'overlay', label: 'class-colored overlay', kind: 'image' },
    ],
    defaults: {
      preset: 'grass_default',
      custom_class_string: 'grass_base:1-8,9-14,16;dirt_base:32;transition:17-31,33-40;props:49-64',
    },
    paramSchema: [
      { key: 'preset', label: 'Class preset', kind: 'select', options: ['grass_default', 'desert', 'snow', 'custom'] },
      { key: 'custom_class_string', label: 'Custom class string', kind: 'textarea' },
    ],
  },
  seam_report: {
    title: 'Seam Report',
    category: 'Inspect',
    color: 'orange',
    icon: 'Chart',
    short: 'SR',
    description: 'Score self-repeat or best-neighbor adjacency for each tile.',
    inputs: [
      { id: 'atlas', label: 'cleaned atlas', kind: 'image', required: true },
      { id: 'classmap', label: 'class map', kind: 'json' },
    ],
    outputs: [
      { id: 'md', label: 'Markdown report', kind: 'md' },
      { id: 'csv', label: 'CSV report', kind: 'csv' },
      { id: 'summary', label: 'score summary', kind: 'json' },
      { id: 'heatmap', label: 'heatmap overlay', kind: 'image' },
    ],
    defaults: {
      mode: 'self-repeat',
      tile_size: 128,
      edge_width: 8,
      include_self: true,
      same_class_only: true,
      only_classes: 'grass_base,dirt_base',
    },
    paramSchema: [
      { key: 'mode', label: 'Mode', kind: 'select', options: ['self-repeat', 'best-neighbor adjacency', 'all comparisons CSV'] },
      { key: 'tile_size', label: 'Tile size', kind: 'number', min: 8, max: 512, step: 8, suffix: 'px' },
      { key: 'edge_width', label: 'Edge width', kind: 'number', min: 1, max: 32, suffix: 'px' },
      { key: 'include_self', label: 'Include self', kind: 'toggle' },
      { key: 'same_class_only', label: 'Same class only', kind: 'toggle' },
      { key: 'only_classes', label: 'Only classes', kind: 'text' },
    ],
  },
  repair: {
    title: 'Base Repair',
    category: 'Cleanup',
    color: 'pink',
    icon: 'Wrench',
    short: 'RP',
    description: 'Repair only base terrain tiles for self-repeat. Never apply to props or transitions.',
    inputs: [
      { id: 'atlas', label: 'cleaned atlas', kind: 'image', required: true },
      { id: 'classmap', label: 'class map', kind: 'json' },
      { id: 'report', label: 'seam report (optional)', kind: 'md' },
    ],
    outputs: [
      { id: 'atlas', label: 'repaired atlas', kind: 'image' },
      { id: 'report', label: 'repair report', kind: 'md' },
      { id: 'metrics', label: 'before/after metrics', kind: 'json' },
    ],
    defaults: {
      tile_size: 128,
      edge_width: 8,
      strength: 0.65,
      tile_ids: '1-8,9-14,16,32',
      only_classes: 'grass_base,dirt_base',
    },
    paramSchema: [
      { key: 'tile_size', label: 'Tile size', kind: 'number', min: 8, max: 512, step: 8, suffix: 'px' },
      { key: 'edge_width', label: 'Edge width', kind: 'number', min: 1, max: 32, suffix: 'px' },
      { key: 'strength', label: 'Strength', kind: 'slider', min: 0, max: 1, step: 0.01 },
      { key: 'tile_ids', label: 'Tile IDs', kind: 'text' },
      { key: 'only_classes', label: 'Only classes', kind: 'text' },
    ],
    warnings: (p) => {
      const ws = [];
      const cls = (p.only_classes || '').toLowerCase();
      if (cls.includes('transition')) ws.push({ level: 'warn', message: 'Repairing transition tiles forces them to self-repeat — they need semantic side labels, not seamlessness.' });
      if (cls.includes('props')) ws.push({ level: 'warn', message: 'Props (rocks, flowers, mushrooms) should not be forced to self-repeat.' });
      if (!cls.trim()) ws.push({ level: 'warn', message: 'No class filter set — base repair will run on every tile, including props.' });
      return ws;
    },
  },
  preview: {
    title: 'Preview Map',
    category: 'Inspect',
    color: 'green',
    icon: 'Eye',
    short: 'PV',
    description: 'Visual QA: stamp tiles into a random or single-tile map for repetition inspection.',
    inputs: [{ id: 'atlas', label: 'atlas', kind: 'image', required: true }],
    outputs: [{ id: 'png', label: 'preview PNG', kind: 'image' }],
    defaults: {
      mode: 'random',
      tile_size: 128,
      only_classes: 'grass_base',
      width: 20,
      height: 20,
      seed: 42,
      tile_number: 8,
    },
    paramSchema: [
      { key: 'mode', label: 'Mode', kind: 'select', options: ['random', 'single'] },
      { key: 'tile_size', label: 'Tile size', kind: 'number', min: 8, max: 512, step: 8, suffix: 'px' },
      { key: 'only_classes', label: 'Only classes', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number', min: 1, max: 64, suffix: 'tiles' },
      { key: 'height', label: 'Height', kind: 'number', min: 1, max: 64, suffix: 'tiles' },
      { key: 'seed', label: 'Seed', kind: 'number', min: 0, max: 9999 },
      { key: 'tile_number', label: 'Tile number (single)', kind: 'number', min: 1, max: 64 },
    ],
  },
  transitions: {
    title: 'Transition Generator',
    category: 'Generate',
    color: 'accent',
    icon: 'Shuffle',
    short: 'TR',
    description: 'Generate semantic transition tiles (edges, corners, island) from two repaired base tiles.',
    inputs: [
      { id: 'atlas_a', label: 'atlas A', kind: 'image', required: true },
      { id: 'atlas_b', label: 'atlas B', kind: 'image', required: true },
    ],
    outputs: [
      { id: 'tiles', label: 'transition tile folder', kind: 'folder' },
      { id: 'manifest', label: 'transition_manifest.yaml', kind: 'yaml' },
    ],
    defaults: {
      preset: 'C_stochastic',
      tile_a: 8,
      name_a: 'grass',
      tile_b: 32,
      name_b: 'dirt',
      tile_size: 128,
      variants: 3,
      noise: 14,
      feather: 0,
      blend_width: 18,
      dither: 36,
      blend_mode: 'stochastic',
      grain_size: 7,
      band_darken: 0,
      band_desaturate: 0,
      highlight_clamp: 255,
      detail_overlay: false,
      detail_count: 0,
      detail_min_size: 1,
      detail_max_size: 5,
      detail_opacity: 0.7,
      detail_mode: 'cross',
      palette_snap: 'none',
      palette_colors: 128,
      palette_max_luma: 175,
      seed: 42,
    },
    paramSchema: [
      { key: 'preset', label: 'Preset', kind: 'select', options: ['A_sharp', 'B_soft_alpha', 'C_stochastic', 'D_clustered', 'E_dark_band', 'F_no_highlight', 'G_soft_detail', 'H_one_way_dirt', 'custom'] },
      { key: 'tile_a', label: 'Tile A', kind: 'number', min: 1, max: 64 },
      { key: 'name_a', label: 'Name A', kind: 'text' },
      { key: 'tile_b', label: 'Tile B', kind: 'number', min: 1, max: 64 },
      { key: 'name_b', label: 'Name B', kind: 'text' },
      { kind: 'section', label: 'Mask & blend' },
      { key: 'variants', label: 'Variants', kind: 'number', min: 1, max: 8 },
      { key: 'noise', label: 'Noise', kind: 'slider', min: 0, max: 64 },
      { key: 'feather', label: 'Feather', kind: 'slider', min: 0, max: 32 },
      { key: 'blend_width', label: 'Blend width', kind: 'slider', min: 0, max: 32 },
      { key: 'dither', label: 'Dither', kind: 'slider', min: 0, max: 96 },
      { key: 'blend_mode', label: 'Blend mode', kind: 'select', options: ['alpha', 'stochastic'] },
      { key: 'grain_size', label: 'Grain size', kind: 'slider', min: 1, max: 16 },
      { kind: 'section', label: 'Band shading' },
      { key: 'band_darken', label: 'Band darken', kind: 'slider', min: 0, max: 0.5, step: 0.01 },
      { key: 'band_desaturate', label: 'Band desaturate', kind: 'slider', min: 0, max: 0.5, step: 0.01 },
      { key: 'highlight_clamp', label: 'Highlight clamp', kind: 'slider', min: 0, max: 255 },
      { kind: 'section', label: 'Detail overlay' },
      { key: 'detail_overlay', label: 'Detail overlay', kind: 'toggle' },
      { key: 'detail_count', label: 'Detail count', kind: 'number', min: 0, max: 400 },
      { key: 'detail_min_size', label: 'Min size', kind: 'number', min: 1, max: 16 },
      { key: 'detail_max_size', label: 'Max size', kind: 'number', min: 1, max: 32 },
      { key: 'detail_opacity', label: 'Opacity', kind: 'slider', min: 0, max: 1, step: 0.01 },
      { key: 'detail_mode', label: 'Detail mode', kind: 'select', options: ['cross', 'b-into-a', 'a-into-b'] },
      { kind: 'section', label: 'Palette' },
      { key: 'palette_snap', label: 'Snap', kind: 'select', options: ['none', 'band', 'all'] },
      { key: 'palette_colors', label: 'Colors', kind: 'number', min: 8, max: 256 },
      { key: 'palette_max_luma', label: 'Max luma', kind: 'number', min: 0, max: 255 },
      { kind: 'section', label: 'Seed' },
      { key: 'seed', label: 'Seed', kind: 'number', min: 0, max: 9999 },
    ],
  },
  contact_sheet: {
    title: 'Contact Sheet',
    category: 'Inspect',
    color: 'orange',
    icon: 'Sheet',
    short: 'CS',
    description: 'Lay out a folder of tile PNGs into a single contact-sheet image.',
    inputs: [{ id: 'tiles', label: 'tile folder', kind: 'folder', required: true }],
    outputs: [{ id: 'png', label: 'contact sheet PNG', kind: 'image' }],
    defaults: { columns: 9, spacing: 1 },
    paramSchema: [
      { key: 'columns', label: 'Columns', kind: 'number', min: 1, max: 32 },
      { key: 'spacing', label: 'Spacing', kind: 'number', min: 0, max: 16, suffix: 'px' },
    ],
    warnings: () => [{ level: 'info', message: 'Contact sheets press unrelated tiles edge-to-edge — they can visually exaggerate seams that aren’t real in-engine.' }],
  },
  extrude: {
    title: 'Extrude / Padding',
    category: 'Export',
    color: 'teal',
    icon: 'Frame',
    short: 'EX',
    description: 'Add 2–4 px extruded padding so Godot/Tiled/browsers don’t bleed across tile edges.',
    inputs: [{ id: 'atlas', label: 'repaired atlas', kind: 'image', required: true }],
    outputs: [{ id: 'atlas', label: 'padded atlas', kind: 'image' }, { id: 'meta', label: 'tiled/godot meta', kind: 'json' }],
    defaults: { tile_size: 128, padding: 2 },
    paramSchema: [
      { key: 'tile_size', label: 'Tile size', kind: 'number', min: 8, max: 512, step: 8, suffix: 'px' },
      { key: 'padding', label: 'Padding', kind: 'number', min: 0, max: 16, suffix: 'px' },
    ],
    warnings: (p) => p.padding < 2 ? [{ level: 'warn', message: 'Padding < 2 px — engine sampling can still bleed across tiles in Godot/Tiled at non-integer zooms.' }] : [],
  },
  dashboard: {
    title: 'Comparison Dashboard',
    category: 'Inspect',
    color: 'accent',
    icon: 'Compare',
    short: 'DB',
    description: 'Side-by-side branch comparison with diff slider, score table, and parameter diff.',
    inputs: [
      { id: 'a', label: 'branch A', kind: 'any', required: true },
      { id: 'b', label: 'branch B', kind: 'any', required: true },
    ],
    outputs: [{ id: 'md', label: 'experiment summary', kind: 'md' }],
    defaults: { lock_seed: true, zoom: 200, filter: 'nearest' },
    paramSchema: [
      { key: 'lock_seed', label: 'Lock seed across branches', kind: 'toggle' },
      { key: 'zoom', label: 'Zoom %', kind: 'slider', min: 100, max: 800, step: 50 },
      { key: 'filter', label: 'Filter', kind: 'select', options: ['nearest', 'linear'] },
    ],
  },
};

const COLOR_TOKENS = {
  blue: { ink: '#2b7fff', soft: '#e8f0ff' },
  teal: { ink: '#0d9488', soft: '#defaf6' },
  violet: { ink: '#7c3aed', soft: '#f0eafe' },
  orange: { ink: '#ea7b2c', soft: '#ffeed8' },
  pink: { ink: '#e94c8b', soft: '#fde7ef' },
  green: { ink: '#1faa6b', soft: '#e6f7ee' },
  accent: { ink: '#5d5cf6', soft: '#eeeefe' },
};

// Pre-populated example pipeline. Coordinates fit a wide canvas.
// Layout: 5 columns, 2 rows, with a comparison dashboard at bottom-right.
const COL_X = [80, 380, 680, 980, 1280, 1580, 1880];
const ROW_Y = [120, 380, 640];

const INITIAL_NODES = [
  { id: 'n_raw', type: 'raw_input', x: COL_X[0], y: ROW_Y[0], status: 'idle', params: {}, runs: 0 },
  { id: 'n_clean', type: 'clean', x: COL_X[1], y: ROW_Y[0], status: 'idle', params: {}, runs: 0 },
  { id: 'n_classify', type: 'classify', x: COL_X[2], y: ROW_Y[0], status: 'idle', params: {}, runs: 0 },
  { id: 'n_seam', type: 'seam_report', x: COL_X[3], y: ROW_Y[0] - 90, status: 'idle', params: {}, runs: 0 },
  { id: 'n_repair', type: 'repair', x: COL_X[3], y: ROW_Y[0] + 90, status: 'idle', params: {}, runs: 0 },
  { id: 'n_preview', type: 'preview', x: COL_X[4], y: ROW_Y[0] - 90, status: 'idle', params: {}, runs: 0 },
  { id: 'n_transitions_C', type: 'transitions', x: COL_X[4], y: ROW_Y[0] + 90, status: 'idle', params: { preset: 'C_stochastic' }, runs: 0, label: 'preset C — stochastic' },
  // Branch: preset G
  { id: 'n_transitions_G', type: 'transitions', x: COL_X[4], y: ROW_Y[1] + 60, status: 'idle', params: { preset: 'G_soft_detail', blend_width: 10, dither: 48, grain_size: 6, band_darken: 0.03, band_desaturate: 0.02, highlight_clamp: 170, detail_overlay: true, detail_count: 90, detail_min_size: 1, detail_max_size: 5, detail_opacity: 0.7, palette_snap: 'band', palette_colors: 128, palette_max_luma: 175, seed: 49 }, runs: 0, label: 'preset G — soft detail' },
  { id: 'n_contact', type: 'contact_sheet', x: COL_X[5], y: ROW_Y[0] + 90, status: 'idle', params: {}, runs: 0 },
  { id: 'n_extrude', type: 'extrude', x: COL_X[5], y: ROW_Y[0] - 90, status: 'idle', params: {}, runs: 0 },
  { id: 'n_dashboard', type: 'dashboard', x: COL_X[6], y: ROW_Y[1] - 80, status: 'idle', params: {}, runs: 0 },
];

const INITIAL_EDGES = [
  { id: 'e1', from: 'n_raw', fromPort: 'atlas', to: 'n_clean', toPort: 'atlas' },
  { id: 'e2', from: 'n_clean', fromPort: 'atlas', to: 'n_classify', toPort: 'atlas' },
  { id: 'e3', from: 'n_clean', fromPort: 'atlas', to: 'n_seam', toPort: 'atlas' },
  { id: 'e4', from: 'n_classify', fromPort: 'classmap', to: 'n_seam', toPort: 'classmap' },
  { id: 'e5', from: 'n_clean', fromPort: 'atlas', to: 'n_repair', toPort: 'atlas' },
  { id: 'e6', from: 'n_classify', fromPort: 'classmap', to: 'n_repair', toPort: 'classmap' },
  { id: 'e7', from: 'n_seam', fromPort: 'md', to: 'n_repair', toPort: 'report' },
  { id: 'e8', from: 'n_repair', fromPort: 'atlas', to: 'n_preview', toPort: 'atlas' },
  { id: 'e9', from: 'n_repair', fromPort: 'atlas', to: 'n_transitions_C', toPort: 'atlas_a' },
  { id: 'e10', from: 'n_repair', fromPort: 'atlas', to: 'n_transitions_C', toPort: 'atlas_b' },
  { id: 'e11', from: 'n_repair', fromPort: 'atlas', to: 'n_transitions_G', toPort: 'atlas_a' },
  { id: 'e12', from: 'n_repair', fromPort: 'atlas', to: 'n_transitions_G', toPort: 'atlas_b' },
  { id: 'e13', from: 'n_transitions_C', fromPort: 'tiles', to: 'n_contact', toPort: 'tiles' },
  { id: 'e14', from: 'n_repair', fromPort: 'atlas', to: 'n_extrude', toPort: 'atlas' },
  { id: 'e15', from: 'n_transitions_C', fromPort: 'tiles', to: 'n_dashboard', toPort: 'a' },
  { id: 'e16', from: 'n_transitions_G', fromPort: 'tiles', to: 'n_dashboard', toPort: 'b' },
];

// Run history (experiment log)
const INITIAL_HISTORY = [];


Object.assign(window, {
  NODE_TYPES, COLOR_TOKENS, INITIAL_NODES, INITIAL_EDGES,
  INITIAL_HISTORY,
});
